language: node_js
install:
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - npm install
script: npm run test-travis
after_success:
  - cat ./coverage/lcov.info|./node_modules/coveralls/bin/coveralls.js
node_js:
  - "0.12"
  - "0.10"
  - "4.0.0"
addons:
    apt:
        packages:
            - xvfb