language: node_js
install:
    - yarn install
script: CI=true yarn test:travis
after_success:
  - cat ./coverage/lcov.info|./node_modules/coveralls/bin/coveralls.js
node_js:
  - 8
addons:
    apt:
        packages:
            - xvfb
