language: node_js
install:
    - yarn install
script: CI=true yarn test
after_success:
  - cat ./coverage/lcov.info|./node_modules/coveralls/bin/coveralls.js
node_js:
  - 6
addons:
    apt:
        packages:
            - xvfb
