version: 2.1

executors:
    node-executor:
        docker:
            - image: circleci/node:14
              environment:
                  CI: true

orbs:
    node: circleci/node@4.0.1

jobs:
    build:
        executor: node-executor
        steps:
            - checkout
            - node/install-packages:
                pkg-manager: yarn

            - run: yarn lint
            - run: yarn lerna run build:check
            - run: yarn lerna run build:test

            - persist_to_workspace:
                  root: .
                  paths: [./*]

    test:
        executor: node-executor
        steps:
            - attach_workspace:
                  at: .

            - run: yarn test -i
            - run: yarn lerna run test:size

    mobx-test:
        executor: node-executor
        steps:
            - attach_workspace:
                  at: .

            - run: yarn mobx test:flow
            - run:
                  command: yarn mobx test:performance
                  environment:
                      PERSIST: true
            - store_artifacts:
                  path: packages/mobx/perf_report
                  destination: mobx-perf

workflows:
    version: 2
    main:
        jobs:
            - build
            - test:
                requires:
                  - "build"
            - mobx-test:
                requires:
                  - "build"
