version: 2.1

executors:
    my-executor:
        docker:
            - image: circleci/node:14
              environment:
                  CI: true

orbs:
    node: circleci/node@4.0.1

jobs:
    build:
        executor: my-executor
        steps:
            - checkout

            - run:
                command: yarn --immutable

            - run: yarn build

            - persist_to_workspace:
                  root: .
                  paths:
                      - ./*

    test-check:
        executor: my-executor
        steps:
            - attach_workspace:
                  at: .

            - run: yarn test:check

    test-performance:
        executor: my-executor
        steps:
            - attach_workspace:
                  at: .

            - run:
                  command: time node --expose-gc test/perf/index.js legacy
                  environment:
                      PERSIST: true

            - run:
                  command: time node --expose-gc test/perf/index.js proxy
                  environment:
                      PERSIST: true

    test-coverage:
        executor: my-executor
        steps:
            - attach_workspace:
                  at: .

            - run: yarn test:coverage
            - persist_to_workspace:
                  root: .
                  paths:
                      - ./coverage

    test-codemod:
        executor: my-executor
        steps:
            - attach_workspace:
                  at: .
            - run:
                  name: run codemod
                  command: |
                      cd packages/mobx-undecorate
                      yarn
                      yarn test

    test-size:
        executor: my-executor
        steps:
            - attach_workspace:
                  at: .

            - run: yarn test:size

    # upload coverage
    upload-coveralls:
        executor: my-executor
        steps:
            - attach_workspace:
                  at: .

            # only run coveralls if the token is present (it is not present for fork PRs for security reasons)
            - run:
                  name: upload coveralls
                  command: |
                      if [[ -v COVERALLS_REPO_TOKEN ]]
                      then
                          cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
                          echo "Coveralls info uploaded"
                      else
                          echo "Warning - Coveralls info could NOT be uploaded since the COVERALLS_REPO_TOKEN was not available"
                      fi

workflows:
    version: 2
    build-and-test:
        jobs:
            - build:
                  filters:
                      branches:
                          ignore:
                              - gh-pages
            - test-check:
                  requires:
                      - build
            - test-performance:
                  requires:
                      - build
            - test-coverage:
                  requires:
                      - build
            - test-size:
                  requires:
                      - build
            - test-codemod:
                  requires:
                      - build
            - upload-coveralls:
                  requires:
                      - test-coverage
